### ISSUE TITLE
CRDs cannot be updated

### ISSUE THREAD

**Issue by lucaschimweg** [Dynatrace/helm-charts#42]
Hey,

due to Helm v3's limitations, updating the chart when a CRD changes is not possible, as Helm v3 does not support upgrading CRDs (as described [in Helm's documentation](https://helm.sh/docs/chart_best_practices/custom_resource_definitions/#some-caveats-and-explanations)).

Is this a known "problem"? Will the CRD change in the future so this has to be considered?

Tagging my PO @loewenstein

**Comment by DTMad** [comment]
Hey,

since we currently use v1beta1 of the CRD this isn't a problem as of now.
We sooner or later will have to switch to v1 (v1beta1 will be removed with version 1.22 of K8s).

Hopefully Helm will find a way to update the CRDs until then - otherwise we will try to find a fix for this problem.

Regards,
Marco
